# Generated by Django 4.1.5 on 2024-02-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='laptop',
        ),
    ]
