# Generated by Django 4.1.5 on 2024-02-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_student_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('movement_type', models.CharField(choices=[('Check Out', 'Check Out'), ('Check In', 'Check In')], max_length=20)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.laptop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
        migrations.RemoveField(
            model_name='laptopregistration',
            name='laptop',
        ),
        migrations.RemoveField(
            model_name='laptopregistration',
            name='student',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RemoveField(
            model_name='theftreport',
            name='laptop',
        ),
        migrations.DeleteModel(
            name='LaptopRegistration',
        ),
        migrations.DeleteModel(
            name='TheftReport',
        ),
    ]
