# Generated by Django 5.0 on 2024-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0004_laptopmovement_remove_laptopregistration_laptop_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="registration_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
