# Generated by Django 5.0 on 2024-02-19 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration",
            "0005_student_course_student_email_student_id_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.student",
            ),
        ),
    ]
