# Generated by Django 5.0 on 2024-02-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0006_laptop_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="laptop",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="laptop",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="laptopmovement",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="laptopmovement",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
